### PR TITLE
Add internationalization

### PR DESCRIPTION
**Pull request by HarisSQA**
Added i18n translator and created a folder with EN and DE languages files. Also added DEBUG : true for development purpuse

### CODE REVIEW

**Review by esaminu — CHANGES_REQUESTED** [review]
Can we remove package-lock.json since yarn will be used for package management in this project. Otherwise LGTM

**Comment by HarisSQA** [comment]
Yes, I will do it right now.

**Comment by HarisSQA** [comment]
Hi @esaminu , 
I still saw conflicts in these files. I rebase main into my branch so this shouldn't be. I test it and everything working fine.

**Review by esaminu — APPROVED** [review]
LGTM ✅

**Pull request merged**
